[project]
name = "seleniumbase-mcp"
readme = "README.md"
requires-python = ">=3.10"
dynamic = [
    "version",
    "license",
    "authors",
    "scripts",
    "keywords",
    "classifiers",
    "description",
    "maintainers",
    "entry-points",
    "dependencies",
    "optional-dependencies",
]

[project.urls]
Homepage = "https://github.com/seleniumbase/seleniumbase-mcp"
Source = "https://github.com/seleniumbase/seleniumbase-mcp"
Repository = "https://github.com/seleniumbase/seleniumbase-mcp"
Documentation = "https://github.com/seleniumbase/seleniumbase-mcp"
Issues = "https://github.com/seleniumbase/seleniumbase-mcp/issues"
SeleniumBase = "https://github.com/seleniumbase/SeleniumBase"

[dependency-groups]  # Used by `uv sync`
dev = [
    "uv>=0.12.8",  # Needed for `mcp dev`
]

[build-system]
requires = ["setuptools>=70.2.0", "wheel>=0.44.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["cdp_server", "driver_server", "sb_server"]

[tool.setuptools.exclude-package-data]
"*" = [".venv*", "build*", "dist*", "uv.lock"]
